server:
  port: 8080

## Postgres --------file to Configuration----------
travel:
  db:
    driver: org.hibernate.dialect.PostgreSQLDialect
    password: pass
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  hbm2ddl:
    auto: none
entitymanager:
  packagesToScan: com.diegojimenez.DBSpringJPa.entity

## Postgres --------Basic Configuration----------
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create #none - create borra la DB y la inicia de 0!!
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/postgres"
#    username: postgres
#    password: pass

## H2 --------Basic Configuration----------

#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
## H2 --------Configuration----------